git-debimport smartmontools_6.2+svn3841.orig.tar.gz

diff --git a/do_release b/do_release
--- a/do_release
+++ b/do_release
@@ -3,27 +3,27 @@
 # do a smartmontools release
 # (C) 2003-11 Bruce Allen <ballen4705@users.sourceforge.net>,
 #             Guido Guenther <agx@sigxcpu.org>
-#             Christian Franke <smartmontools-support@lists.sourceforge.net>
-# $Id: do_release 3282 2011-03-04 19:26:59Z chrfranke $
+# (C) 2006-13 Christian Franke <smartmontools-support@lists.sourceforge.net>
+# $Id: do_release 3765 2013-02-05 17:17:13Z chrfranke $
 
 # Notes on generating releases:
 # (1) update NEWS
-# (2) update CHANGELOG -- put in release number
-# (3) update release number in configure.in 
+# (2) update ChangeLog -- put in release number
+# (3) update release number in configure.ac
 # (4) to test, run without '--commit'
 # (5) when satisfied, add option '--commit'
 
 set -e
 
-# Smartmontools Signing Key (through 2012)
-KEYID=0x2753E77A
+# Smartmontools Signing Key (through 2014)
+KEYID=0x8F6ED8AA
 
 inc_release()
 {
   MINOR=`echo $VERSION | cut -d. -f2`
   MAJOR=`echo $VERSION | cut -d. -f1`
   PERL_OLD=$MAJOR\\.$MINOR
-  ((MINOR++))
+  ((++MINOR))
   NEW_VERSION=$MAJOR.$MINOR
   PERL_NEW=$MAJOR\\.$MINOR	
   NEW_RELEASE="RELEASE_${NEW_VERSION//\./_}"
@@ -63,9 +63,9 @@ fi
 
 (cd $WDROOT && svn status) | while read s; do
   case "`echo $s | tr -s ' '`" in
-    "M "$DIRPAT/smartmontools/CHANGELOG)    echo "$s: OK";;
+    "M "$DIRPAT/smartmontools/ChangeLog)    echo "$s: OK";;
     "M "$DIRPAT/smartmontools/NEWS)         echo "$s: OK";;
-    "M "$DIRPAT/smartmontools/configure.in) echo "$s: OK";;
+    "M "$DIRPAT/smartmontools/configure.ac) echo "$s: OK";;
     *) echo "$s: not allowed"; exit 1;;
   esac
 done
@@ -74,9 +74,9 @@ if [ $? -ne 0 ]; then
 fi
 
 # Get release number
-VERSION=`sed -n 's|^AC_INIT[^,]*, *\([0-9.]*\) *,.*$|\1|p' configure.in`
+VERSION=`sed -n 's|^AC_INIT[^,]*, *\([0-9.]*\) *,.*$|\1|p' configure.ac`
 if [ -z "$VERSION" ]; then
-  echo "AC_INIT not found in configure.in"; exit 1
+  echo "AC_INIT not found in configure.ac"; exit 1
 fi
 VERSIONRC="$VERSION"
 RELEASE="RELEASE_${VERSION//\./_}"
@@ -95,8 +95,8 @@ echo "r$REV: Release $VERSIONRC $RELEASE"
 # Update timestamp
 smartmontools_release_date=`date -u +"%Y-%m-%d"`
 smartmontools_release_time=`date -u +"%T %Z"`
-cat configure.in  | sed "s|smartmontools_release_date=.*|smartmontools_release_date=${smartmontools_release_date}|" > configure.tmp
-cat configure.tmp | sed "s|smartmontools_release_time=.*|smartmontools_release_time=\"${smartmontools_release_time}\"|" > configure.in
+cat configure.ac  | sed "s|smartmontools_release_date=.*|smartmontools_release_date=${smartmontools_release_date}|" > configure.tmp
+cat configure.tmp | sed "s|smartmontools_release_time=.*|smartmontools_release_time=\"${smartmontools_release_time}\"|" > configure.ac
 rm -f configure.tmp
 
 # Review changes
@@ -134,8 +134,8 @@ md5sum $TARFILE > $TARFILE.md5
 if [ -z "$RC" -a "$DIRPAT" = "trunk" ]; then
   inc_release
   if [ "$COMMIT" = "yes" ]; then
-    perl -p -i.bak -e "s/$PERL_OLD/$PERL_NEW/" configure.in
-    # svn commit -m "Bump release number to $NEW_VERSION" configure.in
+    perl -p -i.bak -e "s/$PERL_OLD/$PERL_NEW/" configure.ac
+    # svn commit -m "Bump release number to $NEW_VERSION" configure.ac
   fi
 fi
 
